// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportTicketingNetwork.Database;

namespace TransportTicketingNetwork.Database.Migrations
{
    [DbContext(typeof(TransportTicketingNetworkDbContext))]
    [Migration("20181006140116_AddPayamentAndUSMChanges")]
    partial class AddPayamentAndUSMChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EffectiveDateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpireDateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("'2080-01-01'");

                    b.Property<bool>("IsBlocked");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired();

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<int>("UserRoleId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ApplicationUsers","usm");
                });

            modelBuilder.Entity("Common.Models.ApplicationUserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationUserId");

                    b.Property<DateTime>("EffectiveDateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpireDateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("'2080-01-01'");

                    b.Property<string>("SessionHash")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("SessionHash");

                    b.ToTable("ApplicationUserTokens","usm");
                });

            modelBuilder.Entity("Common.Models.MultiPurposeTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<int>("EnumValue");

                    b.Property<string>("EnumValueName");

                    b.Property<int>("MultiPurposeTagTypeId");

                    b.HasKey("Id");

                    b.HasIndex("MultiPurposeTagTypeId");

                    b.ToTable("MultiPurposeTags","cmn");
                });

            modelBuilder.Entity("Common.Models.MultiPurposeTagType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("EnumName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("MultiPurposeTagTypes","cmn");
                });

            modelBuilder.Entity("Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountBalance");

                    b.Property<int>("ApplicationUserId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte>("GenderEnum");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Users","usm");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("Common.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<byte>("UserRoleEnum");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Modules.Main.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusName");

                    b.Property<string>("BusNumber");

                    b.Property<int?>("BusScheduleId");

                    b.Property<string>("BusType");

                    b.Property<string>("Description");

                    b.Property<int>("NoSeats");

                    b.Property<string>("RouteId");

                    b.Property<int?>("RouteId1");

                    b.HasKey("Id");

                    b.HasIndex("BusScheduleId");

                    b.HasIndex("RouteId1");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("Modules.Main.Models.BusSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Destination");

                    b.Property<string>("EndBusStopId");

                    b.Property<DateTime>("EndTime");

                    b.Property<string>("StartBusStopId");

                    b.Property<DateTime>("StartTime");

                    b.Property<string>("StartingPoint");

                    b.Property<string>("TotalDuration");

                    b.HasKey("Id");

                    b.HasIndex("EndBusStopId");

                    b.HasIndex("StartBusStopId");

                    b.ToTable("BusSchedules");
                });

            modelBuilder.Entity("Modules.Main.Models.BusStop", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BusStopName");

                    b.HasKey("Id");

                    b.ToTable("BusStop");
                });

            modelBuilder.Entity("Modules.Main.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApprovedUserId");

                    b.Property<byte>("PaymentMethod");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("CHAR(24)")
                        .IsFixedLength(true);

                    b.Property<DateTime>("TransactionDateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Modules.Main.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("ExpressFare");

                    b.Property<int>("NormalFare");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Modules.Main.Models.UserExt", b =>
                {
                    b.HasBaseType("Common.Models.User");


                    b.ToTable("UserExt");

                    b.HasDiscriminator().HasValue("UserExt");
                });

            modelBuilder.Entity("Common.Models.ApplicationUser", b =>
                {
                    b.HasOne("Common.Models.UserRole", "UserRole")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Common.Models.ApplicationUserToken", b =>
                {
                    b.HasOne("Common.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserTokens")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Common.Models.MultiPurposeTag", b =>
                {
                    b.HasOne("Common.Models.MultiPurposeTagType", "MultiPurposeTagType")
                        .WithMany("MultiPurposeTags")
                        .HasForeignKey("MultiPurposeTagTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Common.Models.User", b =>
                {
                    b.HasOne("Common.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("User")
                        .HasForeignKey("Common.Models.User", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Modules.Main.Models.Bus", b =>
                {
                    b.HasOne("Modules.Main.Models.BusSchedule")
                        .WithMany("AllocatedBus")
                        .HasForeignKey("BusScheduleId");

                    b.HasOne("Modules.Main.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId1");
                });

            modelBuilder.Entity("Modules.Main.Models.BusSchedule", b =>
                {
                    b.HasOne("Modules.Main.Models.BusStop", "EndBusStop")
                        .WithMany()
                        .HasForeignKey("EndBusStopId");

                    b.HasOne("Modules.Main.Models.BusStop", "StartBusStop")
                        .WithMany()
                        .HasForeignKey("StartBusStopId");
                });

            modelBuilder.Entity("Modules.Main.Models.Payment", b =>
                {
                    b.HasOne("Modules.Main.Models.UserExt", "ApprovedUser")
                        .WithMany("ApprovedPayments")
                        .HasForeignKey("ApprovedUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Modules.Main.Models.UserExt", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
